import type { InstallationClient } from '../github/client.ts';
import { isGitHubStatus, readRepositoryFile } from '../github/content.ts';
import { upsertIssueComment } from '../github/issues.ts';
import {
	type AdversaryWorkflowParams,
	blueQualifies,
	type PurpleTeamResult,
} from './contracts.ts';

export interface PublishedAdversaryBranch {
	branch: string;
	branchSha: string;
	pullRequestNumber: number;
	pullRequestUrl: string;
}

export type AdversaryPublicationInput = Pick<
	AdversaryWorkflowParams,
	'owner' | 'repo' | 'pullNumber' | 'baseSha' | 'deliveryId'
>;

type PullRequestInput = Pick<
	AdversaryWorkflowParams,
	'owner' | 'repo' | 'pullNumber' | 'headSha' | 'baseRef' | 'baseSha'
> &
	Pick<PublishedAdversaryBranch, 'branch' | 'branchSha'>;

export function adversaryCommentMarker(deliveryId: string): string {
	const encoded = [...new TextEncoder().encode(deliveryId)]
		.map((byte) => byte.toString(16).padStart(2, '0'))
		.join('');
	return `<!-- factory-adversary:${encoded} -->`;
}

export function renderAdversaryComment(
	input: AdversaryPublicationInput,
	purple: PurpleTeamResult,
	published?: PublishedAdversaryBranch,
): string {
	if (!published) {
		const decision = blueQualifies(purple)
			? `Purple selected **${escapeModelMarkdown(purple.recommendation)}**, not Blue.`
			: "Blue did not pass Purple's qualification gate.";
		return [
			'## Factory Adversary',
			'',
			`${decision} Confidence: **${escapeModelMarkdown(purple.confidence)}**.`,
			'',
			escapeModelMarkdown(purple.summary),
			'',
			'No alternative pull request was created.',
			'',
			'_Disclosure: The alternative and assessment were generated by AI agents._',
		].join('\n');
	}
	return [
		'## Factory Adversary',
		'',
		`Purple selected **Blue** with ${escapeModelMarkdown(purple.confidence)} confidence.`,
		'',
		escapeModelMarkdown(purple.summary),
		'',
		`[Review alternative PR #${published.pullRequestNumber}](${published.pullRequestUrl})`,
		'',
		`[Compare Blue with its original base](${repositoryUrl(
			input,
			`compare/${input.baseSha}...${published.branchSha}`,
		)})`,
		'',
		'_Disclosure: The alternative and assessment were generated by AI agents. Review and validate the code before use._',
	].join('\n');
}

export async function publishAdversaryComment(
	client: InstallationClient,
	input: AdversaryPublicationInput,
	purple: PurpleTeamResult,
	published?: PublishedAdversaryBranch,
): Promise<number> {
	const marker = adversaryCommentMarker(input.deliveryId);
	return upsertIssueComment(
		client,
		input.owner,
		input.repo,
		input.pullNumber,
		marker,
		renderAdversaryComment(input, purple, published),
	);
}

export async function createAdversaryPullRequest(
	client: InstallationClient,
	input: PullRequestInput,
): Promise<{ pullRequestNumber: number; pullRequestUrl: string }> {
	const pull = await client.rest.pulls.get({
		owner: input.owner,
		repo: input.repo,
		pull_number: input.pullNumber,
	});
	if (
		pull.data.state !== 'open' ||
		pull.data.head.sha.toLowerCase() !== input.headSha.toLowerCase() ||
		pull.data.base.ref !== input.baseRef
	) {
		throw new Error('The original pull request changed before publication.');
	}
	const branch = await client.rest.git.getRef({
		owner: input.owner,
		repo: input.repo,
		ref: `heads/${input.branch}`,
	});
	if (branch.data.object.sha.toLowerCase() !== input.branchSha.toLowerCase()) {
		throw new Error('The published alternative branch changed unexpectedly.');
	}
	const existing = await findAlternativePullRequest(client, input);
	if (existing) return existing;
	const template = await readPullRequestTemplate(client, input);

	try {
		const response = await client.rest.pulls.create({
			owner: input.owner,
			repo: input.repo,
			head: input.branch,
			base: input.baseRef,
			title: `Alternative implementation for #${input.pullNumber}`,
			body: draftPullRequestBody(input, template),
			draft: true,
			request: { retries: 0 },
		});
		return {
			pullRequestNumber: response.data.number,
			pullRequestUrl: response.data.html_url,
		};
	} catch (error) {
		const committed = await findAlternativePullRequest(client, input);
		if (committed) return committed;
		throw error;
	}
}

async function findAlternativePullRequest(
	client: InstallationClient,
	input: PullRequestInput,
): Promise<{ pullRequestNumber: number; pullRequestUrl: string } | null> {
	const pulls = await client.paginate(client.rest.pulls.list, {
		owner: input.owner,
		repo: input.repo,
		head: `${input.owner}:${input.branch}`,
		state: 'open',
		per_page: 100,
	});
	const pull = pulls.find((candidate) => candidate.base.ref === input.baseRef);
	return pull
		? { pullRequestNumber: pull.number, pullRequestUrl: pull.html_url }
		: null;
}

async function readPullRequestTemplate(
	client: InstallationClient,
	input: Pick<PullRequestInput, 'owner' | 'repo' | 'baseSha'>,
): Promise<string | null> {
	const paths = [
		'.github/pull_request_template.md',
		'.github/PULL_REQUEST_TEMPLATE.md',
		'pull_request_template.md',
		'PULL_REQUEST_TEMPLATE.md',
		'docs/pull_request_template.md',
		'docs/PULL_REQUEST_TEMPLATE.md',
	];
	for (const path of paths) {
		try {
			return await readRepositoryFile(
				client,
				input.owner,
				input.repo,
				path,
				input.baseSha,
			);
		} catch (error) {
			if (!isGitHubStatus(error, 404)) throw error;
		}
	}
	return null;
}

function draftPullRequestBody(
	input: PullRequestInput,
	template: string | null,
): string {
	const originalUrl = repositoryUrl(input, `pull/${input.pullNumber}`);
	const compareUrl = repositoryUrl(
		input,
		`compare/${input.baseSha}...${input.branchSha}`,
	);
	const context = [
		`Purple selected this alternative implementation over [#${input.pullNumber}](${originalUrl}).`,
		'',
		`[Compare this alternative with its original base](${compareUrl}).`,
		'',
		'Factory created this as a draft so maintainers can make the final decision.',
	].join('\n');
	return template?.trim()
		? `${template.trimEnd()}\n\n---\n\n${context}`
		: context;
}

export function escapeModelMarkdown(value: string): string {
	return value
		.replaceAll('&', '&amp;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;')
		.replace(/([\\`*_{}[\]()#+.!|~-])/g, '\\$1');
}

function repositoryUrl(
	input: { owner: string; repo: string },
	path: string,
): string {
	return `https://github.com/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.repo)}/${path}`;
}
