import * as v from 'valibot';
import { describe, expect, it } from 'vitest';
import { fixVerdictSchema } from '../src/triage/contracts.ts';
import { prContentSchema } from '../src/triage/pipeline-contracts.ts';
import {
	prContentPrompt,
	prWritingInstructions,
} from '../src/triage/prompts.ts';

describe('PR writing prompts', () => {
	it('uses the built-in pull request template', () => {
		const prompt = prContentPrompt(123, 'factory/fix-123', 'main');

		expect(prompt).toContain('## Changes');
		expect(prompt).toContain('## Testing');
		expect(prompt).toContain('## Docs');
		expect(prompt).toContain('Closes #123');
		expect(prompt).not.toContain('auto-generated by the triage bot');
		expect(prompt).not.toContain('confirmed the fix');
	});

	it('adds repository-specific skill guidance', () => {
		const prompt = prWritingInstructions(123, {
			name: 'astro-pr-writer',
			directory: '.agents/skills/astro-pr-writer',
		});

		expect(prompt).toContain('Activate the `astro-pr-writer` skill');
		expect(prompt).toContain('.agents/skills/astro-pr-writer/SKILL.md');
		expect(prompt).toContain('## Changes');
	});

	it('rejects pull request bodies that do not follow the template', () => {
		const invalidPr = {
			title: 'Fix the issue',
			body: '## Summary\n\nThe fix.\n\n## Confirmation\n\nIt works.',
		};
		expect(() => v.parse(prContentSchema, invalidPr)).toThrow(
			'Changes, Testing, and Docs',
		);
		expect(() =>
			v.parse(prContentSchema, {
				title: 'Fix the issue',
				body: [
					'```markdown',
					'## Changes',
					'## Testing',
					'## Docs',
					'```',
				].join('\n'),
			}),
		).toThrow('Changes, Testing, and Docs');
		expect(() =>
			v.parse(fixVerdictSchema, {
				status: 'confirmed',
				reasoning: 'The reporter confirmed the fix.',
				pr: invalidPr,
			}),
		).toThrow('Changes, Testing, and Docs');

		expect(() =>
			v.parse(prContentSchema, {
				title: 'Fix the issue',
				body: [
					'## Changes',
					'',
					'- Fixes the issue.',
					'',
					'## Testing',
					'',
					'- Adds a regression test.',
					'',
					'## Docs',
					'',
					'- No docs needed.',
				].join('\n'),
			}),
		).not.toThrow();
	});
});
